language: php
php:
  - 7.1
before_script:
  - composer self-update
  - composer install
  - mv .env_test .env
notifications:
  email:
    recipients:
      - webmaster@ezjj7.com
      - l496501043@163.com
    on_success: always # default: change
    on_failure: always # default: always