language: php
php:
- 7.1
before_script:
- composer self-update
- composer install
- mv .env_test .env
notifications:
  email:
    recipients:
    - webmaster@zjj7.com
    - l496501043@163.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_04c5b7bbfe4f_key -iv $encrypted_04c5b7bbfe4f_iv
  -in travis.enc -out travis -d
- chmod 600 travis
#- echo -e "Host 120.77.223.127:22\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
addons:
  ssh_known_hosts: 120.77.223.127:22
# after_success时，登录服务器，并从GitHub上拉取代码(代码目录下需要有.git信息)
after_success:
- ssh -p 22 'mkdir -p /home/www/php/zjjbnb_api'