language: php
php:
- 7.1
before_script:
- composer self-update
- composer install
- mv .env_test .env
notifications:
  email:
    recipients:
    - webmaster@zjj7.com
    - l496501043@163.com
    on_success: always
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_04c5b7bbfe4f_key -iv $encrypted_04c5b7bbfe4f_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
