language: php
php:
- 7.1
before_script:
- composer self-update
- composer install
- mv .env_test .env
notifications:
  email:
    recipients:
    - webmaster@zjj7.com
    - l496501043@163.com
    on_success: always
    on_failure: always
before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_04c5b7bbfe4f_key -iv $encrypted_04c5b7bbfe4f_iv
  -in id_rsa.enc -out /home/travis/.ssh/id_rsa -d
- chmod 600 /home/travis/.ssh/id_rsa
- ssh-add /home/travis/.ssh/id_rsa
- echo -e "Host 120.77.223.127\n\tStrictHostKeyChecking no\n" >> /home/travis/.ssh/config
addons:
  ssh_known_hosts: 120.77.223.127:22
after_success:
- ssh root@120.77.223.127 -p 22 'cd /home/www/php/zjjbnb_api && git pull'
